name: demoActions

on:
  # push: 
  #   branches: main

  issues:
    types: opened

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: run as sample job
        run: echo hellow world 

      - name: Demo123
        uses: actions/upload-artifact@v4
        with: 
          name: testArtifact
          path: $({github.workspace})
  deploy: 
    runs-on: windows-latest
    
    steps: 
      - uses: actions/download-artifact@v4
        with: 
         name: build-artifect
         path: $({github.workspace})

